"""Mock disease / pest detection service.

IMPORTANT: no computer-vision model runs here. The result is derived deterministically
from the uploaded image bytes so the same image always yields the same result, and every
response is flagged `is_mock=True` with a disclaimer.

To plug in a real model, implement `VisionDetector.predict(image_bytes, crop)` against a
TFLite/ONNX classifier and register it in `get_detector()`. The response schema does not
change.
"""
from __future__ import annotations

import hashlib
from abc import ABC, abstractmethod

from app.core.time import now
from app.domain.enums import Severity
from app.schemas.agronomy import DetectionResult

DISCLAIMER = ("Prototype output. This result is generated by a mock analysis service, not a "
              "trained computer-vision model. Confirm with field inspection or an agronomist "
              "before applying any treatment.")

CATALOG = {
    "Tomato": [
        {"condition": "Early blight (Alternaria solani)", "type": "Fungal disease",
         "cause": "Warm days with extended leaf wetness; splash dispersal from infected debris.",
         "action": "Remove affected lower leaves, avoid overhead irrigation, and apply a "
                   "protectant fungicide such as mancozeb at label rate.",
         "followups": ["Re-scout 5 lower leaves after 3 days",
                       "Log any spread to neighbouring rows",
                       "Keep foliage dry through the evening"]},
        {"condition": "Leaf miner damage (Liriomyza spp.)", "type": "Pest damage",
         "cause": "Adult flies laying in leaf tissue; larvae tunnel through the mesophyll.",
         "action": "Install yellow sticky traps, remove heavily mined leaves and consider a "
                   "neem-based spray before larval populations peak.",
         "followups": ["Count mines per leaf on 10 plants",
                       "Check trap catch after 48 hours"]},
        {"condition": "Nitrogen deficiency (visual indication)", "type": "Nutrient deficiency",
         "cause": "Low available nitrogen or leaching after heavy irrigation.",
         "action": "Apply a split nitrogen dose through fertigation and re-assess new growth "
                   "after 7 days. Confirm with a soil test before large applications.",
         "followups": ["Compare new vs older leaf colour in 5 days",
                       "Book a soil nutrient test"]},
    ],
    "Paddy": [
        {"condition": "Bacterial leaf blight (Xanthomonas oryzae)", "type": "Bacterial disease",
         "cause": "Standing water plus wind injury; spreads rapidly after heavy rain.",
         "action": "Drain the field for 2-3 days, stop nitrogen top-dressing and remove severely "
                   "affected tillers.",
         "followups": ["Inspect field margins first", "Recheck after drainage"]},
        {"condition": "Brown planthopper infestation", "type": "Pest infestation",
         "cause": "Dense canopy with high humidity at the plant base.",
         "action": "Part the canopy and inspect the base of tillers, drain intermittently and "
                   "avoid broad-spectrum sprays that kill natural predators.",
         "followups": ["Count hoppers on 10 hills", "Check for hopper burn patches"]},
    ],
    "Chilli": [
        {"condition": "Thrips damage (Scirtothrips dorsalis)", "type": "Pest damage",
         "cause": "Hot dry weather favouring rapid thrips multiplication.",
         "action": "Use blue sticky traps, maintain soil moisture, and rotate an approved "
                   "insecticide to avoid resistance.",
         "followups": ["Check curled young leaves", "Record trap counts twice weekly"]},
        {"condition": "Anthracnose (Colletotrichum spp.)", "type": "Fungal disease",
         "cause": "Extended humidity and rain splash onto maturing fruit.",
         "action": "Remove and destroy infected fruit, improve airflow, and apply a protectant "
                   "fungicide before the next wet spell.",
         "followups": ["Inspect maturing fruit daily", "Keep harvested fruit dry"]},
    ],
}

GENERIC = {"condition": "No clear disease signature detected", "type": "Inconclusive",
           "cause": "Image quality, lighting or framing may be limiting the analysis.",
           "action": "Retake the photo in daylight, filling the frame with a single affected "
                     "leaf, and submit again.",
           "followups": ["Photograph both leaf surfaces", "Include a healthy leaf for comparison"]}


class Detector(ABC):
    model_name: str
    model_version: str
    is_mock: bool

    @abstractmethod
    def predict(self, image_bytes: bytes, crop: str) -> dict: ...


class MockDetector(Detector):
    model_name = "mock-vision-classifier"
    model_version = "0.1.0-prototype"
    is_mock = True

    def predict(self, image_bytes: bytes, crop: str) -> dict:
        digest = hashlib.sha256(image_bytes).hexdigest()
        seed = int(digest[:8], 16)
        options = CATALOG.get(crop, CATALOG["Tomato"])
        if seed % 17 == 0:
            primary, confidence = GENERIC, 0.31
        else:
            primary = options[seed % len(options)]
            confidence = round(0.62 + (seed % 3300) / 10000, 2)

        affected = round(4 + (seed % 4200) / 100, 1)
        severity = (Severity.CRITICAL if affected > 34 else
                    Severity.HIGH if affected > 20 else
                    Severity.MEDIUM if affected > 9 else Severity.INFO)

        alternatives = []
        for i, alt in enumerate(options):
            if alt["condition"] == primary["condition"]:
                continue
            alternatives.append({
                "condition": alt["condition"], "type": alt["type"],
                "confidence": round(max(0.04, confidence - 0.22 - i * 0.11), 2)})
        return {"primary": primary, "confidence": confidence, "severity": severity,
                "affected_area_pct": affected, "alternatives": alternatives[:2]}


_detector: Detector = MockDetector()


def get_detector() -> Detector:
    """Swap in a real ONNX/TFLite classifier here — the API contract is unchanged."""
    return _detector


def analyze(image_bytes: bytes, image_name: str, field_id: str, crop: str) -> DetectionResult:
    detector = get_detector()
    out = detector.predict(image_bytes, crop)
    p = out["primary"]
    return DetectionResult(
        id="det-" + hashlib.sha1(image_bytes[:2048] + image_name.encode()).hexdigest()[:10],
        field_id=field_id, crop=crop, image_name=image_name, image_size_bytes=len(image_bytes),
        suspected_condition=p["condition"], condition_type=p["type"],
        confidence=out["confidence"], severity=out["severity"],
        affected_area_pct=out["affected_area_pct"], possible_cause=p["cause"],
        recommended_action=p["action"], followups=p["followups"],
        alternatives=out["alternatives"], analyzed_at=now(),
        model_name=detector.model_name, model_version=detector.model_version,
        is_mock=detector.is_mock, disclaimer=DISCLAIMER)
