import secrets

from fastapi import Depends, Request
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer

from app.core.config import settings
from app.core.errors import DomainError
from app.core.time import now
from app.domain.enums import DataSource
from app.schemas.auth import UserPublic
from app.schemas.common import Meta
from app.services import auth_service

bearer_scheme = HTTPBearer(auto_error=False)


def current_user_dep(
    credentials: HTTPAuthorizationCredentials | None = Depends(bearer_scheme),
) -> UserPublic:
    """Required authentication. Raises 401 with a message safe to show a user."""
    if credentials is None or not credentials.credentials:
        raise DomainError("Sign in to continue.", 401, "not_authenticated")
    return auth_service.current_user(credentials.credentials)


def protected(
    credentials: HTTPAuthorizationCredentials | None = Depends(bearer_scheme),
) -> UserPublic | None:
    """Applied to the farm data routers. Enforced unless AUTH_REQUIRED=false, which
    exists only for local API work without a token."""
    if not settings.auth_required:
        return None
    if credentials is None or not credentials.credentials:
        raise DomainError("Sign in to continue.", 401, "not_authenticated")
    return auth_service.current_user(credentials.credentials)


def device_or_user(
    request: Request,
    credentials: HTTPAuthorizationCredentials | None = Depends(bearer_scheme),
) -> str:
    """Ingest accepts either a signed-in user (for manual testing) or a device key.

    Field nodes cannot complete an interactive sign-in, so they present
    `X-Device-Key`, compared against INGEST_API_KEY from the environment. With no key
    configured and AUTH_REQUIRED=false the endpoint is open for local bench work.
    """
    device_key = request.headers.get("x-device-key")
    if settings.ingest_api_key and device_key:
        if secrets.compare_digest(device_key, settings.ingest_api_key):
            return "device"
        raise DomainError("Device key rejected.", 401, "invalid_device_key")
    if credentials and credentials.credentials:
        auth_service.current_user(credentials.credentials)
        return "user"
    if not settings.auth_required:
        return "open"
    raise DomainError(
        "Ingest requires a device key (X-Device-Key) or a signed-in session.", 401,
        "not_authenticated")


def make_meta(source: DataSource = DataSource.MEASURED, note: str | None = None,
              text_engine: str = "rules") -> Meta:
    from app.i18n import current_language
    simulated = settings.is_simulated
    effective = DataSource.SIMULATED if simulated and source == DataSource.MEASURED else source
    return Meta(
        generated_at=now(),
        data_source=effective,
        simulated=simulated,
        engine_version=f"rules-0.1.0/derive-0.1.0",
        language=current_language(), text_engine=text_engine,
        note=note or ("Sensor values are generated by the mock source; the response contract is "
                      "identical to real ESP32 hardware." if simulated else None),
    )


def envelope(data, source: DataSource = DataSource.MEASURED, note: str | None = None,
             text_engine: str = "rules") -> dict:
    return {"data": data, "meta": make_meta(source, note, text_engine)}
